harry 
hermione 
ron 
arthur 
molly 
bill 
charlie 
percy 
fredI 
george 
ginny 
ollivander 
sirius_article  
hagrid_article  
hooch_article  
lockhart_article  
lupin_article  
mcgonagall_article  
madeye_article  
quirrell_article  
slughorn_article  
snape_article  
sprout_article  
trelawney_article  
james_potterI_article  
lily_potter_article  
winky_article  
albus_dumbledore_article  
flitwick_article  
abbott_article  
crabbe_article  
golye_article  
diggory_article  
finnigan_article  
longbottom_article  
lovegood_article  
malfoy_article  
shacklebolt_article  
tonks_article  
umbridge_article  
delacour_article  
gabby_delacour_article  
krum_article  
maxime_article  
karkaroff_article  
lestrange_article  
lucius_malfoy_article  
narcissa_malfoy_article  
pettigrew_article  
riddle_article  
dobby_article  
aberforth_article  
gregorovitch_article  
james_potterII_article  
albus_potter_article  
lily_luna_potter_article  
rose_granger_weasley_article  
hugo_granger_weasley_article  
audrey_weasley_article  
victoire_weasley_article  
dominique_weasley_article  
louis_weasley_article  
angelina_johnson_article  
fred_weasleyII_article  
roxanne_weasley_article  
molly_weasleyII_article  
lucy_weasley_article  
teddy_lupin_article  

# Notes about webpage design:
# -Link harry potter wiki webpage

