harry  
hermione  
ron  
arthur  
molly  
bill  
charlie  
percy  
fredI  
george  
ginny  
ollivander  
sirius   
hagrid   
hooch   
lockhart   
lupin   
mcgonagall   
madeye   
quirrell   
slughorn   
snape   
sprout   
trelawney   
james_potterI   
lily_potter   
winky   
albus_dumbledore   
flitwick   
abbott   
crabbe   
golye   
diggory   
finnigan   
longbottom   
lovegood   
malfoy   
shacklebolt   
tonks   
umbridge   
delacour   
gabby_delacour   
krum   
maxime   
karkaroff   
lestrange   
lucius_malfoy   
narcissa_malfoy   
pettigrew   
riddle   
dobby   
aberforth   
gregorovitch   
james_potterII   
albus_potter   
lily_luna_potter   
rose_granger_weasley   
hugo_granger_weasley   
audrey_weasley   
victoire_weasley   
dominique_weasley   
louis_weasley   
angelina_johnson   
fred_weasleyII   
roxanne_weasley   
molly_weasleyII   
lucy_weasley   
teddy_lupin   
isolt_sayre  
william_sayre  
rionach_sayre  
james_steward  
chadwick_boot
webster_boot  
josefina_calderon  
martha_steward  
rionach_steward  
gormlaith_gaunt
william_the_pukwudgie  
godric_gryffindor  
rowena_ravenclaw  
helga_hufflepuff  
salazar_slytherin  

# Wand names:
harry_wand  
hermione_wand  
ron_wand  
arthur_wand  
molly_wand  
bill_wand  
charlie_wand  
percy_wand  
fredI_wand  
george_wand  
ginny_wand  
ollivander_wand  
sirius_wand   
hagrid_wand   
hooch_wand   
lockhart_wand   
lupin_wand   
mcgonagall_wand   
madeye_wand   
quirrell_wand   
slughorn_wand   
snape_wand   
sprout_wand   
trelawney_wand   
james_potterI_wand   
lily_potter_wand   
winky_wand   
albus_dumbledore_wand   
flitwick_wand   
abbott_wand   
crabbe_wand   
golye_wand   
diggory_wand   
finnigan_wand   
longbottom_wand   
lovegood_wand   
malfoy_wand   
shacklebolt_wand   
tonks_wand   
umbridge_wand   
delacour_wand   
gabby_delacour_wand   
krum_wand   
maxime_wand   
karkaroff_wand   
lestrange_wand   
lucius_malfoy_wand   
narcissa_malfoy_wand   
pettigrew_wand   
riddle_wand   
dobby_wand   
aberforth_wand   
gregorovitch_wand   
james_potterII_wand   
albus_potter_wand   
lily_luna_potter_wand   
rose_granger_weasley_wand   
hugo_granger_weasley_wand   
audrey_weasley_wand   
victoire_weasley_wand   
dominique_weasley_wand   
louis_weasley_wand   
angelina_johnson_wand   
fred_weasleyII_wand   
roxanne_weasley_wand   
molly_weasleyII_wand   
lucy_weasley_wand   
teddy_lupin_wand   
isolt_sayre_wand  
william_sayre_wand  
rionach_sayre_wand  
james_steward_wand  
chadwick_boot_wand
webster_boot_wand  
josefina_calderon_wand  
martha_steward_wand  
rionach_steward_wand  
gormlaith_gaunt_wand
william_the_pukwudgie_wand  
godric_gryffindor_wand  
rowena_ravenclaw_wand  
helga_hufflepuff_wand  
salazar_slytherin_wand

# accounts
harry_account  
hermione_account  
ron_account  
arthur_account  
molly_account  
bill_account  
charlie_account  
percy_account  
fredI_account  
george_account  
ginny_account  
ollivander_account  
sirius_account   
hagrid_account   
hooch_account   
lockhart_account   
lupin_account   
mcgonagall_account   
madeye_account   
quirrell_account   
slughorn_account   
snape_account   
sprout_account   
trelawney_account   
james_potterI_account   
lily_potter_account   
winky_account   
albus_dumbledore_account   
flitwick_account   
abbott_account   
crabbe_account   
golye_account   
diggory_account   
finnigan_account   
longbottom_account   
lovegood_account   
malfoy_account   
shacklebolt_account   
tonks_account   
umbridge_account   
delacour_account   
gabby_delacour_account   
krum_account   
maxime_account   
karkaroff_account   
lestrange_account   
lucius_malfoy_account   
narcissa_malfoy_account   
pettigrew_account   
riddle_account   
dobby_account   
aberforth_account   
gregorovitch_account   
james_potterII_account   
albus_potter_account   
lily_luna_potter_account   
rose_granger_weasley_account   
hugo_granger_weasley_account   
audrey_weasley_account   
victoire_weasley_account   
dominique_weasley_account   
louis_weasley_account   
angelina_johnson_account   
fred_weasleyII_account   
roxanne_weasley_account   
molly_weasleyII_account   
lucy_weasley_account   
teddy_lupin_account   
isolt_sayre_account  
william_sayre_account  
rionach_sayre_account  
james_steward_account  
chadwick_boot_account
webster_boot_account  
josefina_calderon_account  
martha_steward_account  
rionach_steward_account  
gormlaith_gaunt_account
william_the_pukwudgie_account  
godric_gryffindor_account  
rowena_ravenclaw_account  
helga_hufflepuff_account  
salazar_slytherin_account

# Articles 

harry_article  
hermione_article  
ron_article  
arthur_article  
molly_article  
bill_article  
charlie_article  
percy_article  
fredI_article  
george_article  
ginny_article  
ollivander_article  
sirius_article   
hagrid_article   
hooch_article   
lockhart_article   
lupin_article   
mcgonagall_article   
madeye_article   
quirrell_article   
slughorn_article   
snape_article   
sprout_article   
trelawney_article   
james_potterI_article   
lily_potter_article   
winky_article   
albus_dumbledore_article   
flitwick_article   
abbott_article   
crabbe_article   
golye_article   
diggory_article   
finnigan_article   
longbottom_article   
lovegood_article   
malfoy_article   
shacklebolt_article   
tonks_article   
umbridge_article   
delacour_article   
gabby_delacour_article   
krum_article   
maxime_article   
karkaroff_article   
lestrange_article   
lucius_malfoy_article   
narcissa_malfoy_article   
pettigrew_article   
riddle_article   
dobby_article   
aberforth_article   
gregorovitch_article   
james_potterII_article   
albus_potter_article   
lily_luna_potter_article   
rose_granger_weasley_article   
hugo_granger_weasley_article   
audrey_weasley_article   
victoire_weasley_article   
dominique_weasley_article   
louis_weasley_article   
angelina_johnson_article   
fred_weasleyII_article   
roxanne_weasley_article   
molly_weasleyII_article   
lucy_weasley_article   
teddy_lupin_article   
isolt_sayre_article  
william_sayre_article  
rionach_sayre_article  
james_steward_article  
chadwick_boot_article
webster_boot_article  
josefina_calderon_article  
martha_steward_article  
rionach_steward_article  
gormlaith_gaunt_article
william_the_pukwudgie_article  
godric_gryffindor_article  
rowena_ravenclaw_article  
helga_hufflepuff_article  
salazar_slytherin_article

# Pet class
harry_pet  
hermione_pet  
ron_pet  
arthur_pet  
molly_pet  
bill_pet  
charlie_pet  
percy_pet  
fredI_pet  
george_pet  
ginny_pet  
ollivander_pet  
sirius_pet   
hagrid_pet   
hooch_pet   
lockhart_pet   
lupin_pet   
mcgonagall_pet   
madeye_pet   
quirrell_pet   
slughorn_pet   
snape_pet   
sprout_pet   
trelawney_pet   
james_potterI_pet   
lily_potter_pet   
winky_pet   
albus_dumbledore_pet   
flitwick_pet   
abbott_pet   
crabbe_pet   
golye_pet   
diggory_pet   
finnigan_pet   
longbottom_pet   
lovegood_pet   
malfoy_pet   
shacklebolt_pet   
tonks_pet   
umbridge_pet   
delacour_pet   
gabby_delacour_pet   
krum_pet   
maxime_pet   
karkaroff_pet   
lestrange_pet   
lucius_malfoy_pet   
narcissa_malfoy_pet   
pettigrew_pet   
riddle_pet   
dobby_pet   
aberforth_pet   
gregorovitch_pet   
james_potterII_pet   
albus_potter_pet   
lily_luna_potter_pet   
rose_granger_weasley_pet   
hugo_granger_weasley_pet   
audrey_weasley_pet   
victoire_weasley_pet   
dominique_weasley_pet   
louis_weasley_pet   
angelina_johnson_pet   
fred_weasleyII_pet   
roxanne_weasley_pet   
molly_weasleyII_pet   
lucy_weasley_pet   
teddy_lupin_pet   
isolt_sayre_pet  
william_sayre_pet  
rionach_sayre_pet  
james_steward_pet  
chadwick_boot_pet
webster_boot_pet  
josefina_calderon_pet  
martha_steward_pet  
rionach_steward_pet  
gormlaith_gaunt_pet
william_the_pukwudgie_pet  
godric_gryffindor_pet  
rowena_ravenclaw_pet  
helga_hufflepuff_pet  
salazar_slytherin_pet

# Notes about webpage design:
# -Link harry potter wiki webpage

